config/routes.rb
FoodShop::Application.routes.draw do
  resources :devices

  resources :applications

  

end

app/models/application.rb
class Application < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => true
end

app/models/device.rb
class Device < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_action :set_application, only: [:show, :edit, :update, :destroy]
  layout "genyx"

  # GET /applications
  # GET /applications.json
  def index
    @applications = Application.all
  end

  # GET /applications/1
  # GET /applications/1.json
  def show
  end

  # GET /applications/new
  def new
    @application = Application.new
  end

  # GET /applications/1/edit
  def edit
  end

  # POST /applications
  # POST /applications.json
  def create
    @application = Application.new(application_params)

    respond_to do |format|
      if @application.save
        format.html { redirect_to @application, notice: 'Application was successfully created.' }
        format.json { render action: 'show', status: :created, location: @application }
      else
        format.html { render action: 'new' }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applications/1
  # PATCH/PUT /applications/1.json
  def update
    respond_to do |format|
      if @application.update(application_params)
        format.html { redirect_to @application, notice: 'Application was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applications/1
  # DELETE /applications/1.json
  def destroy
    @application.destroy
    respond_to do |format|
      format.html { redirect_to applications_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_application
      @application = Application.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def application_params
      params.require(:application).permit(:name)
    end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]
  layout "genyx"

  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.all
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render action: 'show', status: :created, location: @device }
      else
        format.html { render action: 'new' }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:device_id, :user_id, :channel_id, :root, :application_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def side_nav_with_li(text, class_name, url)
    content_tag(:li, side_nav_without_li(text, class_name, url))
  end

  def side_nav_without_li(text, class_name, url)
    li_class = 'icon20 ' + class_name
    link_to(content_tag(:span, content_tag(:i, nil, class: li_class), class:'icon') + content_tag(:span, text, class: 'txt'), url)
  end
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/applications/_form.html.haml
.widget
  .widget-title
    .icon
      %i.icon20.i-stack-checkmark
    %h4 Application

  .widget-content
    = simple_form_for @application, :html => { :class => 'form-horizontal' } do |f|
      = f.input :name, input_html: { class: 'span12' }
      .form-actions
        = f.button :submit, :class => 'btn btn-primary'
        = link_to 'Cancel', applications_path, :class => 'btn'

app/views/applications/edit.html.haml
= content_for(:crumb) do
  .crumb
    %ul.breadcrumb
      %li= link_to(content_tag(:i, nil, class: 'icon16 i-home-4') + "Home", '#') + content_tag(:span, '/', class: 'divider')
      %li= link_to("Applications", applications_path) + content_tag(:span, '/', class: 'divider')
      %li.active Edit Applications

= content_for(:heading) do
  #heading.page-header
    %h1= content_tag(:i, nil, class: 'icon20 i-rocket') + ' Edit Applications'

= render :partial => 'form'

app/views/applications/index.html.haml
= content_for(:crumb) do
  .crumb
    %ul.breadcrumb
      %li= link_to(content_tag(:i, nil, class: 'icon16 i-home-4') + "Home", '#') + content_tag(:span, '/', class: 'divider')
      / %li= link_to("Library", '#') + content_tag(:span, '/', class: 'divider')
      %li.active Applications

= content_for(:heading) do
  #heading.page-header
    %h1= content_tag(:i, nil, class: 'icon20 i-rocket') + ' Applications'


%table.table.table-striped.table-bordered
  %thead
    %tr
      %th #
      %th Application Name
      %th User Count
      %th Root Count
      %th
  %tbody
    - @applications.each do |app|
      %tr
        %td.center= app.id
        %td= app.name
        %td.center 0
        %td.center 0
        %td.center.vcenter
          .btn-group
            = link_to content_tag(:i, nil, class:'icon12 i-eye') + ' Show', app, class: 'btn btn-mini'
            = link_to content_tag(:i, nil, class:'icon12 i-pencil') + ' Edit', edit_application_path(app), class: 'btn btn-mini'
            = link_to content_tag(:i, nil, class:'icon12 i-remove') + ' Delete', application_path(app), class: 'btn btn-danger btn-mini', :method => :delete, :data => { :confirm => 'Are you sure?' }


= link_to 'New Application', new_application_path, class: 'btn btn-primary'

app/views/applications/new.html.haml
= content_for(:crumb) do
  .crumb
    %ul.breadcrumb
      %li= link_to(content_tag(:i, nil, class: 'icon16 i-home-4') + "Home", '#') + content_tag(:span, '/', class: 'divider')
      %li= link_to("Applications", applications_path) + content_tag(:span, '/', class: 'divider')
      %li.active New Applications

= content_for(:heading) do
  #heading.page-header
    %h1= content_tag(:i, nil, class: 'icon20 i-rocket') + ' New Applications'

= render :partial => 'form'

app/views/applications/show.html.haml
= content_for(:crumb) do
  .crumb
    %ul.breadcrumb
      %li= link_to(content_tag(:i, nil, class: 'icon16 i-home-4') + "Home", '#') + content_tag(:span, '/', class: 'divider')
      %li= link_to("Applications", applications_path) + content_tag(:span, '/', class: 'divider')
      %li.active Application

= content_for(:heading) do
  #heading.page-header
    %h1= content_tag(:i, nil, class: 'icon20 i-rocket') + ' Application'


%table.table.table-bordered
  %tr
    %th.span3 #
    %td= @application.id
  %tr
    %th Application Name
    %td= @application.name
  %tr
    %th User Count
    %td 0
  %tr
    %th Root Count
    %td

.button_wrap
  = link_to content_tag(:i, nil, class:'icon12 i-arrow-left') + ' Back', :back, class: 'btn'
  = link_to content_tag(:i, nil, class:'icon12 i-pencil') + ' Edit', edit_application_path(@application), class: 'btn'

app/views/devices/_form.html.haml
.widget
  .widget-title
    .icon
      %i.icon20.i-stack-checkmark
    %h4 Device

  .widget-content
    = simple_form_for @device, :html => { :class => 'form-horizontal' } do |f|
      = f.input :device_id, input_html: { class: 'span12' }
      = f.input :user_id, input_html: { class: 'span12' }
      = f.input :channel_id, input_html: { class: 'span12' }
      = f.input :root
      = f.input :application_id, input_html: { class: 'span12' }
      .form-actions
        = f.button :submit, :class => 'btn btn-primary'
        = link_to 'Cancel', devices_path, :class => 'btn'

app/views/devices/edit.html.haml
= content_for(:crumb) do
  .crumb
    %ul.breadcrumb
      %li= link_to(content_tag(:i, nil, class: 'icon16 i-home-4') + "Home", '#') + content_tag(:span, '/', class: 'divider')
      %li= link_to("Applications", applications_path) + content_tag(:span, '/', class: 'divider')
      %li.active Edit Applications

= content_for(:heading) do
  #heading.page-header
    %h1= content_tag(:i, nil, class: 'icon20 i-rocket') + ' Edit Applications'

= render :partial => 'form'

app/views/devices/index.html.haml
= content_for(:crumb) do
  .crumb
    %ul.breadcrumb
      %li= link_to(content_tag(:i, nil, class: 'icon16 i-home-4') + "Home", '#') + content_tag(:span, '/', class: 'divider')
      / %li= link_to("Library", '#') + content_tag(:span, '/', class: 'divider')
      %li.active Devices

= content_for(:heading) do
  #heading.page-header
    %h1= content_tag(:i, nil, class: 'icon20 i-users') + ' Devices'

%table.table.table-striped.table-bordered
  %thead
    %tr
      %th Device
      %th User ID
      %th Channel ID
      %th Root
      %th Application
      %th
  %tbody
    - @devices.each do |device|
      %tr
        %td= device.device_id
        %td.center= device.user_id
        %td.center= device.channel_id
        %td.center= device.root
        %td.center= device.application_id
        %td.center.vcenter
          .btn-group
            / = link_to 'Show', device
            = link_to content_tag(:i, nil, class:'icon12 i-pencil') + ' Edit', edit_device_path(device), class: 'btn btn-mini'
            = link_to content_tag(:i, nil, class:'icon12 i-remove') + ' Delete', device, class: 'btn btn-danger btn-mini', :method => :delete, :data => { :confirm => 'Are you sure?' }

= link_to 'New Device', new_device_path, class: 'btn btn-primary'

app/views/devices/new.html.haml
= content_for(:crumb) do
  .crumb
    %ul.breadcrumb
      %li= link_to(content_tag(:i, nil, class: 'icon16 i-home-4') + "Home", '#') + content_tag(:span, '/', class: 'divider')
      %li= link_to("Devices", devices_path) + content_tag(:span, '/', class: 'divider')
      %li.active New Device

= content_for(:heading) do
  #heading.page-header
    %h1= content_tag(:i, nil, class: 'icon20 i-user') + ' New Device'

= render :partial => 'form'

app/views/devices/show.html.haml
%p#notice= notice

%p
  %b Device:
  = @device.device_id
%p
  %b User:
  = @device.user_id
%p
  %b Channel:
  = @device.channel_id
%p
  %b Root:
  = @device.root
%p
  %b Application:
  = @device.application_id

= link_to 'Edit', edit_device_path(@device)
\|
= link_to 'Back', devices_path

app/views/layouts/_header.html.haml
%header#header.navbar.navbar-inverse.navbar-fixed-top
  .navbar-inner
    .container-fluid
      = link_to image_tag("logo.png", alt: "Genyx admin"), "#", class: 'brand'
      .nav-no-collapse
        #top-search
        %ul.nav.pull-right
          %li.divider-vertical
          %li.dropdown
            = link_to content_tag(:i, nil, class: 'icon24 i-bell-2') + content_tag(:span, 6 , class: 'notification red'), "#", class: 'dropdown-toggle', "data-toggle" => "dropdown"
            %ul.dropdown-menu
              %li= link_to content_tag(:i, nil, class: 'icon16 i-calendar-2') + "Admin Jenny add event", "#"
              %li= link_to content_tag(:i, nil, class: 'icon16 i-file-zip') + "User Dexter attach file", "#"
              %li= link_to content_tag(:i, nil, class: 'icon16 i-stack-picture') + "User Dexter attach 3 pictures", "#"
              %li
                = link_to content_tag(:i, nil, class: 'icon16 i-cart-add') + "New orders" + content_tag(:span, 2, class: 'notification green'), "#"
              %li
                = link_to content_tag(:i, nil, class: 'icon16 i-bubbles-2') + "New comments" + content_tag(:span, 5, class: 'notification red'), "#"
              %li
                = link_to content_tag(:i, nil, class: 'icon16 i-pie-5') + "Daily stats is generated", "#"
          %li.divider-vertical
          %li.dropdown
            = link_to content_tag(:i, nil, class: 'icon24 i-envelop-2') + content_tag(:span, 3 , class: 'notification red'), "#", class: 'dropdown-toggle', "data-toggle" => "dropdown"
            %ul.dropdown-menu.messages
              %li.head
                %h4 Index
                = content_tag(:span, "3 messages", class: 'count')
                = content_tag(:span, link_to(content_tag(:i, nil, class:'icon16 i-pencil-5'), '#', class: 'tipB'), class: 'new-msg').html_safe
              %li
                - text_1 = ""
                - text_1 += content_tag(:span, image_tag("/assets/avatars/peter.jpg"), class: 'avatar')
                - text_1 += content_tag(:span, "Call me i need to talk with you", class: 'msg')
                - text_1 += content_tag(:button, content_tag(:i, nil, class: 'icon12 i-close-2'), class: 'btn close')
                = link_to text_1.html_safe, '#', class: 'clearfix'
              %li
                - text_2 = ""
                - text_2 += content_tag(:span, image_tag("/assets/avatars/anonime.jpg"), class: 'avatar')
                - text_2 += content_tag(:span, "I have question about ...", class: 'msg')
                - text_2 += content_tag(:button, content_tag(:i, nil, class: 'icon12 i-close-2'), class: 'btn close')
                = link_to text_2.html_safe, '#', class: 'clearfix'
              %li.foot= link_to "View all messages", "#"
          %li.divider-vertical
          %li.dropdown.user
            = link_to image_tag("/assets/avatars/sugge.jpg") + content_tag(:span, content_tag(:i, nil, class: 'icon16 i-arrow-down-2'), class: 'more'), "#", class: 'dropdown-toggle avatar', "data-toggle" => "dropdown"
            %ul.dropdown-menu
              %li= link_to content_tag(:i, nil, class: 'icon16 i-cogs') + "Settings", '#'
              %li= link_to content_tag(:i, nil, class: 'icon16 i-user') + "Profile", '#'
              %li= link_to content_tag(:i, nil, class: 'icon16 i-exit') + "Logout", '#'
          %li.divider-vertical

app/views/layouts/_sidebar.html.haml
%aside#sidebar
  .side-options
    %ul
      %li= link_to content_tag(:i, nil, class: 'icon16 i-arrow-left-7'), '#', class: 'act act-primary tip', id: 'collapse-nav', title: 'Collapse navigation'
  .sidebar-wrapper
    %nav#mainnav
      %ul.nav.nav-list
        = side_nav_with_li("Dashboard", 'i-screen', '#')
        = side_nav_with_li("Applications", 'i-rocket', applications_path)
        = side_nav_with_li("Devices", 'i-users', devices_path)
        / = side_nav_with_li("Dashboard", 'i-screen', '#')
        / = side_nav_with_li("Charts", 'i-stats-up', '#')
        / %li
        /   = side_nav_without_li("Forms", 'i-menu-6', '#')
        /   %ul.sub
        /     = side_nav_with_li("Form elements", 'i-stack-list', '#')
        /     = side_nav_with_li("Form validation", 'i-stack-checkmark', '#')
        /     = side_nav_with_li("Form wizard", 'i-stack-star', '#')
        / %li
        /   = side_nav_without_li("Tables", 'i-table-2', '#')
        /   %ul.sub
        /     = side_nav_with_li("Static tables", 'i-table', '#')
        /     = side_nav_with_li("Data tables", 'i-table', '#')
        / = side_nav_with_li("Grid", 'i-grid-5', '#')
        / = side_nav_with_li("Typography", 'i-font', '#')
        / = side_nav_with_li("Calendar", 'i-calendar', '#')
        / %li
        /   = side_nav_without_li("Ui Elements", 'i-cogs', '#')
        /   %ul.sub
        /     = side_nav_with_li("Icons", 'i-IcoMoon', '#')
        /     = side_nav_with_li("Buttons", 'i-point-up', '#')
        /     = side_nav_with_li("UI Elements", 'i-puzzle', '#')
        / = side_nav_with_li("Gallery", 'i-images', '#')
        / = side_nav_with_li("Maps", 'i-location-4', '#')
        / = side_nav_with_li("File manager", 'i-cloud-upload', '#')
        / = side_nav_with_li("Widgets", 'i-cube-3', '#')
        / %li
        /   = side_nav_without_li("Pages", 'i-file-8', '#')
        /   %ul.sub
        /     %li
        /       = side_nav_without_li("Error Pages", 'i-warning', '#')
        /       %ul.sub
        /         = side_nav_with_li("Error 403", 'i-notification', '#')
        /         = side_nav_with_li("Error 404", 'i-notification', '#')
        /         = side_nav_with_li("Error 405", 'i-notification', '#')
        /         = side_nav_with_li("Error 500", 'i-notification', '#')
        /         = side_nav_with_li("Error 503", 'i-notification', '#')
        /         = side_nav_with_li("Offline page", 'i-notification', '#')
        /       = side_nav_with_li("Invoice Pages", 'i-credit', '#')
        /       = side_nav_with_li("Profile Pages", 'i-user', '#')
        /       = side_nav_with_li("Search page", 'i-search-2', '#')
        /       = side_nav_with_li("Email page", 'i-envelop-2', '#')
        /       = side_nav_with_li("Support page", 'i-support', '#')
        /       = side_nav_with_li("FAQ page", 'i-question', '#')
        /       = side_nav_with_li("Blank page", 'i-file-7', '#')

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "FoodShop" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">FoodShop</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/layouts/genyx.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Genyx admin v1.0</title>
    <%= csrf_meta_tags %>

    <!-- Headings -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,800,700' rel='stylesheet' type='text/css'>
    <!-- Text -->
    <link href='http://fonts.googleapis.com/css?family=Droid+Sans:400,700' rel='stylesheet' type='text/css' />

     <!--[if lt IE 9]>
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400" rel="stylesheet" type="text/css" />
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:700" rel="stylesheet" type="text/css" />
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:800" rel="stylesheet" type="text/css" />
    <link href="http://fonts.googleapis.com/css?family=Droid+Sans:400" rel="stylesheet" type="text/css" />
    <link href="http://fonts.googleapis.com/css?family=Droid+Sans:700" rel="stylesheet" type="text/css" />
    <![endif]-->

    <!-- app stylesheets -->
    <%= stylesheet_link_tag "application", :media => "all" %>

    <!--[if IE 8]><link href="css/ie8.css" rel="stylesheet" type="text/css" /><![endif]-->

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      </script><script src="js/html5shiv.js"></script></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="images/ico/apple-touch-icon-57-precomposed.png">
    <link rel="shortcut icon" href="images/ico/favicon.png">

  </head>
  <body>
    <%= render "layouts/header" %>

    <div class="main">
        <%= render "layouts/sidebar" %>

        <section id="content">
            <div class="wrapper">
                <%= yield(:crumb) %>

                <div class="container-fluid">
                    <%= yield(:heading) %>


                    <div class="row-fluid">
                    <!-- Start page from here  -->

                        <%= yield %>

                    </div><!-- End .row-fluid  -->

                </div> <!-- End .container-fluid  -->
            </div> <!-- End .wrapper  -->
        </section>
    </div><!-- End .main  -->
    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
  </body>
</html>